apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortner-reader.fullname" . }}
  labels: {{- include "url-shortner-reader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector: {{- include "url-shortner-reader.selectorLabels" . | nindent 4 }}
